project:
  type: website
  pre-render:
    - python scripts/openalex_to_yaml.py
    # - sass styles/custom.scss:_site/styles/custom.css

jupyter:
  kernel: quarto-venv

website:
  title: "Attila Cangi"
  site-url: "https://acangi.github.io"
  description: "Personal website of Attila Cangi."
  page-navigation: true
  open-graph: true                          # social cards
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
        icon: book
      - href: teaching.qmd
        text: Teaching
        icon: mortarboard
  page-footer:
    center: "© 2025 Attila Cangi · [Impressum (Disclaimer)](/disclaimer.qmd) · Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: cosmo
    css: _site/styles/custom.css
    toc: false
    include-in-header: _includes/head_meta.html
    

markdown_extensions:
  - attr_list
