---
title: "Attila Cangi"
about: 
  template: marquee #marquee #solana #trestles #broadside #jolla
  image-shape: round
title-block-author: false
title-block-keywords: false
title-block-description: false
meta:
  - name: description
    content: "Personal website of Attila Cangi."
  - name: keywords
    content: "Attila Cangi, Machine Learning, Materials Design, AI, Artificial Intelligence, Electronic Structure, DFT, Atomistic Simulations, Novel Materials"
toc: false
#css: /styles/custom.scss
title-block-banner: true
---

Attila Cangi is the head of the <a href="https://www.casus.science/?page_id=4660" target="_blank">Department of Machine Learning for Materials Design</a> at the <a href="https://www.casus.science" target="_blank">Center for Advanced Systems Understanding</a>, <a href="https://www.hzdr.de" target="_blank">Helmholtz-Zentrum Dresden-Rossendorf</a>. 

Together with his team, he conducts research on applying artificial intelligence and machine learning to computational materials modeling. He develops scalable machine-learning methods that accelerate first-principles simulations of electronic and atomistic structures, with the overarching goal of discovering and designing novel materials.

He received his Ph.D. in Chemistry from the University of California, Irvine, and previously worked as a postdoctoral fellow at the Max Planck Institute of Microstructure Physics and as a staff member at Sandia National Laboratories.

Information on his research, research group, teaching activities, and recent news is available on his <a href="https://www.casus.science/?page_id=4660" target="_blank">institutional website</a>.


## CV
<object data="https://www.hzdr.de/db/Cms?pOid=67820" type="application/pdf" width="100%" height="800px">
  <p>Your browser can't display this PDF. <a href="https://www.hzdr.de/db/Cms?pOid=67820">Download it instead</a>.</p>
</object>